# Generated by Django 6.0.5 on 2026-05-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('poids', '⚖️ Poids'), ('force', '💪 Force'), ('exercice', '🏃 Exercices journaliers'), ('autre', '🏅 Autre')], max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Emoji représentant le badge (ex: 🏆)', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Ex: A atteint son objectif de poids', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('fitness', 'Fitness'), ('dance', 'Dance')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reussite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('est_proprietaire', models.BooleanField(default=False, help_text="Cocher si c'est ta propre réussite")),
                ('date_reussite', models.DateField(help_text="Date à laquelle l'objectif a été atteint")),
                ('description', models.TextField(help_text="Ex: J'ai réalisé 50 pompes d'affilée !")),
                ('photo', models.ImageField(blank=True, help_text='Photo illustrant la réussite (optionnel)', null=True, upload_to='reussites/')),
                ('active', models.BooleanField(default=False, help_text='Cocher pour publier la réussite sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.badge')),
            ],
            options={
                'ordering': ['-date_reussite'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('tiktok_url', models.URLField(help_text='URL de la vidéo TikTok')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorie')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
