# Generated by Django 6.0.5 on 2026-05-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reussite',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='reussite',
            name='est_proprietaire',
        ),
        migrations.RemoveField(
            model_name='reussite',
            name='photo',
        ),
        migrations.AddField(
            model_name='reussite',
            name='lien_post',
            field=models.URLField(blank=True, help_text='Lien vers leur post (Instagram, Facebook, LinkedIn...)', null=True),
        ),
        migrations.AddField(
            model_name='reussite',
            name='reseau_social',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='reussite',
            name='titre',
            field=models.CharField(default='', help_text="Ex: J'ai perdu 2kg !", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reussite',
            name='type',
            field=models.CharField(choices=[('moi', 'Ma réussite'), ('visiteur', 'Réussite visiteur')], default='moi', max_length=10),
        ),
        migrations.AlterField(
            model_name='reussite',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reussite',
            name='date_reussite',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reussite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reussite',
            name='nom',
            field=models.CharField(help_text='Ton nom ou celui du visiteur', max_length=100),
        ),
        migrations.CreateModel(
            name='ReussiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('tiktok', 'Vidéo TikTok')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reussites/')),
                ('tiktok_url', models.URLField(blank=True, help_text='URL TikTok si type = vidéo', null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('reussite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.reussite')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
